openapi: 3.0.3
info:
  title: Payment Gateway API
  description: API for payment gateway services
  version: 1.0.0

servers:
  - url: /api/v1
    description: Development server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the application
      operationId: healthCheck
      tags:
        - Health
      responses:
        '200':
          description: Application is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  
  /payment/modes:
    get:
      summary: Get available payment modes
      description: Returns the available payment modes
      operationId: getPaymentModes
      tags:
        - Payment
      responses:
        '200':
          description: Payment modes retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentModesResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /payment/initiate:
    post:
      summary: Initiate a payment transaction
      description: Initiates a payment transaction with the specified payment details
      operationId: initiatePayment
      tags:
        - Payment
      parameters:
        - name: userId
          in: header
          required: true
          schema:
            type: string
          description: ID of the user making the payment
        - name: Idempotency-Key
          in: header
          required: true
          schema:
            type: string
            format: uuid
          description: Client-generated unique key for idempotency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentInitiateRequest'
      responses:
        '200':
          description: Payment initiated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: "UP"
          description: Current health status of the service
        timestamp:
          type: string
          format: date-time
          example: "2025-05-24T12:00:00Z"
          description: Current server time
    
    PaymentModesResponse:
      type: object
      properties:
        paymentModes:
          type: array
          items:
            $ref: '#/components/schemas/PaymentMode'
    
    PaymentMode:
      type: object
      properties:
        modeCode:
          type: string
          example: "UPI"
          description: Payment mode code
        modeName:
          type: string
          example: "Unified Payment Interface"
          description: Payment mode name
        description:
          type: string
          example: "Direct bank transfer using UPI"
          description: Payment mode description
        isActive:
          type: boolean
          example: true
          description: Whether this payment mode is active
        paymentTypes:
          type: array
          items:
            $ref: '#/components/schemas/PaymentType'
    
    PaymentType:
      type: object
      properties:
        typeCode:
          type: string
          example: "GOOGLE_PAY"
          description: Payment type code
        typeName:
          type: string
          example: "Google Pay"
          description: Payment type name
        description:
          type: string
          example: "Pay using Google Pay UPI"
          description: Payment type description
        isActive:
          type: boolean
          example: true
          description: Whether this payment type is active
    
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          format: int32
          example: 500
          description: HTTP status code
        message:
          type: string
          example: "An error occurred"
          description: Error message
        timestamp:
          type: string
          format: date-time
          example: "2025-05-24T12:00:00Z"
          description: Timestamp when the error occurred
    
    PaymentInitiateRequest:
      type: object
      required:
        - amount
        - paymentMode
        - paymentType
      properties:
        amount:
          type: number
          format: decimal
          example: 100.00
          description: Payment amount
        paymentMode:
          type: string
          example: "UPI"
          description: Payment mode (UPI, CREDIT_CARD, DEBIT_CARD)
        paymentType:
          type: string
          example: "GOOGLE_PAY"
          description: Payment type (GOOGLE_PAY, PHONE_PE, VISA, MASTERCARD)
        currency:
          type: string
          default: "INR"
          example: "INR"
          description: Currency code
        metadata:
          type: object
          additionalProperties: true
          description: Additional metadata for the payment
          example:
            orderId: "ORDER123"
            productId: "PROD456"
    
    PaymentResponse:
      type: object
      properties:
        paymentId:
          type: string
          example: "PAY123456"
          description: Unique payment ID
        status:
          type: string
          example: "PENDING"
          description: Payment status (PENDING, PROCESSING, SUCCEEDED, FAILED, CANCELLED)
        amount:
          type: number
          format: decimal
          example: 100.00
          description: Payment amount
        currency:
          type: string
          example: "INR"
          description: Currency code
        paymentMode:
          type: string
          example: "UPI"
          description: Payment mode
        paymentType:
          type: string
          example: "GOOGLE_PAY"
          description: Payment type
        vendorTransactionId:
          type: string
          example: "UPI_abc123"
          description: Transaction ID from the payment provider
        timestamp:
          type: string
          format: date-time
          example: "2025-05-24T12:00:00Z"
          description: Timestamp of the payment
        metadata:
          type: object
          additionalProperties: true
          description: Additional metadata for the payment
