spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  redis:
    host: localhost
    port: 6379
    password: redispass
    timeout: 2000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: -1ms

# Logging
logging:
  level:
    root: INFO
    org:
      springframework: INFO
      jooq: INFO
      data.redis: INFO
